drahnr/cargo-spellcheck

- .concourse.yml
- src/action/interactive.rs
Handles exits during interactive mode.
> ctrl-c handling

- src/action/interactive.rs
- src/checker/hunspell.rs
- src/checker/mod.rs
- src/config.rs
- src/documentation.rs
Bug Fix
closes #21 .
do not error if search paths do not contain dic/aff files
> hunspell config and affixes

- src/action/bandaid.rs
- src/action/interactive.rs
Feature
partially solves #23  .
An additional item in the list, which can be edited.
Based on #23 @zhiburt
> interactive ui - allow custom mistake replacements

- src/action/interactive.rs
Get rid of a few magic literals for printing the interactive dialog.
> refactor/interactive: introduce constants and remove magic literals

- src/action/interactive.rs
- src/action/mod.rs
- src/documentation/markdown.rs
- src/main.rs
Refactor #63 and builds on top of #61 which is refactored in the process.
closes #63.
Introduce an intermediate representation between found mistakes and exit code, called `Finish`.
Partially refactored your existing code and moved a few things around, I tried to cover all test cases manually - <kbd>ShouldWork™</kbd>
> bail handling refactor

- src/action/interactive.rs
- src/action/mod.rs
- src/documentation/markdown.rs
- src/main.rs
Refactor #63 and builds on top of #61 which is refactored in the process.
closes #63.
Introduce an intermediate representation between found mistakes and exit code, called `Finish`.
Partially refactored your existing code and moved a few things around, I tried to cover all test cases manually - <kbd>ShouldWork™</kbd>
Equiv to #66
> refactor singal handling

- Cargo.toml
- README.md
Fixes #14 thanks to @msuesskraut who did all the work here!
> chore/hunspell: update to v0.2.0

- Cargo.lock
- Cargo.toml
- README.md
- src/action/bandaid.rs
- src/checker/dummy.rs
- src/checker/mod.rs
- src/documentation/chunk.rs
- src/documentation/cluster.rs
- src/documentation/literal.rs
- src/documentation/literalset.rs
- src/documentation/mod.rs
- src/main.rs
- src/span.rs
- src/suggestion.rs
- src/traverse/iter.rs
- src/traverse/mod.rs
- src/util.rs
@laysauchoa I have a few questions about a few variable names which I will post inline
> rebased and refactored pr 65

- src/action/mod.rs
- src/checker/dummy.rs
- src/documentation/chunk.rs
- src/documentation/literal.rs
- src/documentation/literalset.rs
- src/documentation/markdown.rs
- src/documentation/mod.rs
- src/span.rs
- src/util.rs
Handle UTF8 chars properly 🚤🌴
* Bug Fix
Closes #78 
All ranges are characters, all lengths are in chars too.
> feat/utf8: add test for unicode chars

- README.md
- src/checker/hunspell.rs
- src/checker/quirks.rs
- src/config.rs
> fix/quirks: allow concatenation was inverted, added counterpart + tests

- Cargo.lock
- src/action/bandaid.rs
- src/action/interactive.rs
- src/action/mod.rs
- src/checker/mod.rs
- src/config/mod.rs
- src/documentation/literal.rs
- src/documentation/markdown.rs
- src/documentation/mod.rs
- src/span.rs
- src/suggestion.rs
- src/traverse/iter.rs
- src/traverse/mod.rs
- src/util.rs
* 🩹 Bug Fix
@laysauchoa  you should be able to push to this branch directly
Ref #102 .
Closes #97.
> url part of footnotes and links shall not be checked

- .config/lingo.dic
- .config/spellcheck.toml
- README.md
- demo/.config/spellcheck.toml
- demo/README.md
- src/action/mod.rs
- src/checker/dummy.rs
- src/checker/hunspell.rs
- src/checker/mod.rs
- src/config/mod.rs
- src/documentation/chunk.rs
- src/documentation/literalset.rs
- src/documentation/markdown.rs
- src/documentation/mod.rs
- src/span.rs
- src/suggestion.rs
- src/traverse/mod.rs
* 🩹 Bug Fix
* 🪣 Misc
Closes #107 .
Cleans up the logic and adds additional tests around common mark file parsing.
> commonmark handling refactor

- Cargo.lock
- Cargo.toml
- src/documentation/markdown.rs
> chore/cargo: update dependencies and address fallout

- .concourse.yml
- .config/spellcheck.toml
- Cargo.lock
- Cargo.toml
- README.md
- src/action/mod.rs
- src/config/mod.rs
- src/documentation/chunk.rs
- src/documentation/literalset.rs
- src/documentation/mod.rs
- src/documentation/tests.rs
- src/main.rs
- src/reflow/config.rs
- src/reflow/mod.rs
- src/reflow/tests.rs
- src/suggestion.rs
- src/util.rs
* 🩹 Bug Fix
* 🪣 Misc
Closes #128 .
Closes #126 .
Add run checks to CI, assure it's not going to break again.
Addition debug logs for reflow.
Assorted debug adjustments (only singlethreaded checker execution).
> reflow fixup for README.md / cmark

- .github/ISSUE_TEMPLATE/---report-a-bug.md
- README.md
> documentation chores

- README.md
Showcase usage with a git commit hook
> doc/git: add section on git hook usage

- Cargo.lock
- Cargo.toml
- src/action/interactive.rs
- src/main.rs
Make sure <kbd>ESC</kbd>/<kbd>q</kbd> for action `fix` is treated differently from <kbd>Ctrl</kbd>+<kbd>C</kbd>
* 🩹 Bug Fix
* 🪣 Misc
<!---
Introduce another user selection variant.
> fix UI abort is not eq quit

- .concourse.yml
- .config/lingo.dic
- src/checker/hunspell.rs
Add a unit test to verify provided extra dictionary is 
a) is used
b) and accepts the words as described in the extra dict as ok
* 🩹 Bug Fix
Adds a unit test, not sure how to resolve the issue entirely
> hunspell extra dic fixup

- .concourse.yml
- demo/.config/topic.dic
* 🪣 Misc
Reduce the number of compilations to one, and pass on the changes via `input`/`output` transitions.
> ci efficiency

- Cargo.lock
- Cargo.toml
- src/config/args.rs
> fix/args: allow , separate list of checkers as flag arg

- src/suggestion.rs
> chore/warn: avoid repeated warnings for missing terminal size

- README.md
- demo/member/procmacro/Cargo.toml
- demo/member/procmacro/src/lib.rs
- src/traverse/mod.rs
* 🩹 Bug Fix
Closes #176 .
Introduces a workaround for https://gitlab.com/crates.rs/cargo_toml/-/issues/5
> traverse workaround

- src/action/mod.rs
- src/config/args.rs
- src/main.rs
- src/traverse/iter.rs
- src/traverse/mod.rs
Add a subcommand that lists all files that are being collected.
Also adds info level logs to each file being checked and how many mistakes were found.
* 🦚 Feature
> list files

- src/checker/tokenize.rs
> fix/tokenize: improve logic around ticks

- REMEDY.md
Add documentation on how to fix spell checks of particular kinds.
Closes # .
> doc: add remedy.md

- src/config/args.rs
Avoid early return if a `Cargo.toml` is present, that does not provide `metadata.spellcheck` key.
* 🩹 Bug Fix
> fix/args: spellcheck key is optional

- src/checker/mod.rs
- src/checker/tokenize.rs
- src/documentation/literal.rs
- src/documentation/literalset.rs
- src/documentation/tests.rs
Introduces test cases for #226 and #227 and eventually fixes for both.
* 🩹 Bug Fix
Closes #227, closes #226.
> feat/test: add test cases for corner cases

- Cargo.toml
- src/action/interactive.rs
- src/action/mod.rs
- src/documentation/literal.rs
- src/documentation/literalset.rs
> fix/interactive: add missing ticked original check

- demo/Cargo.toml
- src/action/mod.rs
- src/documentation/chunk.rs
- src/documentation/mod.rs
- src/traverse/mod.rs
> complete PR 35

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/action/interactive.rs
- src/action/mod.rs
- src/config/args.rs
- src/lib.rs
> 🦖-clap-clap

- Cargo.lock
- Cargo.toml
- README.md
- src/config/args.rs
- src/lib.rs
> 🦕-clap-clap: autoderive shell for completions

- src/documentation/cluster.rs
- src/documentation/developer.rs
- src/documentation/tests.rs
* 🩹 Bug Fix
Closes #257
Fix clustering in dev comments for spaces in code blocks.
> dev comments cluster fix

- Cargo.lock
- Cargo.toml
- src/traverse/iter.rs
- src/traverse/mod.rs
> quiet warnings on non cargo dirs with git

- .concourse.yml
- Cargo.lock
- Cargo.toml
- doc-chunks/Cargo.toml
> concourse owner fixin

- .github/pull_request_template.md
- src/config/args.rs
* 🪣 Misc
Just cleaning up two small typos I saw.
N/A
> Fix minor typo

- .concourse.yml
- Cargo.lock
- Cargo.toml
Update dependencies and update the concourse ci yaml such that the release pipeline works again.
* 🪣 Misc
> chores again

- .concourse.yml
- Cargo.lock
- Cargo.toml
> binstall compat artifact names

- Cargo.lock
- Cargo.toml
- demo/.config/spellcheck.toml
- demo/Cargo.toml
- src/config/iso.rs
- src/config/mod.rs
- src/traverse/mod.rs
> Bump toml related dependcies

- src/action/mod.rs
- Improves checking times by ~10x
comparison with `cargo-spellcheck 0.12.4` by running `cargo spellcheck` on https://github.com/rust-lang/rust/tree/22e9fe644ea710eec50cb0aabcae7fa8dd9fd675
(see below note for why I've done `-j $(nproc)`
```console
$ hyperfine "cargo spellcheck -j $(nproc)" "~/code/cargo-spellcheck/target/release/cargo-spellcheck -j $(nproc)" --export-markdown hyperfine.md 
Benchmark 1: cargo spellcheck -j 16
Time (mean ± σ):     356.515 s ± 11.933 s    [User: 409.724 s, System: 155.652 s]
Range (min … max):   340.755 s … 374.962 s    10 runs
Benchmark 2: ~/code/cargo-spellcheck/target/release/cargo-spellcheck -j 16
Time (mean ± σ):     32.953 s ±  2.922 s    [User: 353.613 s, System: 13.498 s]
Range (min … max):   26.296 s … 36.698 s    10 runs
Summary …
```
> Parallelize checking for 10x performance win

- Cargo.lock
- Cargo.toml
Make edition 2024 work.
* 🩹 Bug Fix
Closes #345  .
> fix: rust edition 2024 compatibility
