- src/main.rs
- src/traverse.rs
The `config` subcommand now either prints the default config with `--stdout`, writes the default config to the default user config with `--user` or to a custom path with `--cfg=<cfg>`.
Issues:
- since last subcommand had no required options, calling `cargo spellcheck config` was mistaken to be a call to this subcommand with `config` being interpreted as option `<paths>...`. I quickly fixed this by making `(--fix|--interactive)` required, but that's certainly not as required right? Whats the purpose of this last subcommand?
- should `cargo spellcheck --stdout` print the currently saved config instead of the default one?
- help message states that if `--cfg` is a directory, it attempts to open `cargo_spellchecl.toml` in that directory but that's not the case for `config`
Additionally: added …
> [WIP] Clarify config subcommand

- src/action/interactive.rs
If `?` is pressed in interactive mode, stay on the current suggestion by recursively calling `user_input()` after printing `HELP`.
Adding the newlines to the `HELP` string is a workaround to avoid loosing some entries due to cursor moves in the selection code.
> Interactive: don't advance to next suggestion on help message

- src/action/interactive.rs
If user's terminal got resized in `interactive` mode he/she would get a panic.
```
thread 'main' panicked at 'internal error: entered unreachable code: Unexpected return when dealing with user input', src/action/interactive.rs:320:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> fix/interactive: terminal resize while waiting user input caused crash

- src/action/interactive.rs
When custom input is chosen the movements were mixed up.
@drahnr sorry for the delay in the fixes I had to do :). #30 Looks great.
And as #23 is closed I'd like to say thank you for `Good first issue` labels :)
> Fix interactive chose movements

- src/checker/hunspell.rs
I bet it's unnecessary to put at output at least by `dbg!` :)
> fix/hunspell: remove debug message

- src/action/interactive.rs
This adds a cursor movement and inserting a character in *arbitrary* place.
Truly saying I got confused implementing that in order of complexity.
Might it would be better to split responsibilities of rendering the general list of suggestions from the custom line.
In this case there would be no need in rendering the whole suggestion list one more time.
And the complexity would be reduced just because each part of interface is responsible for one thing. (I see that it's what should have been done but ... :)).
yep. I consider the code this PR providing is slightly compound :(
PS: These thoughts I have in order to not thinking that my code *just* bad :smiley:
> feature/interactive: add insert mode

- Cargo.lock
- Cargo.toml
- src/main.rs
closes #34  .
Add a signal-hook for `SIGINT`, `SIGTERM` and `SIGQUIT` (not sure here) to properly disable raw terminal mode.
How is this testable? Manual testing showed it's working.
I'm not hundert percent happy with`on_exit()`, is the exit ok that way?
> feat/signals: exit raw terminal mode on SIGTERM, SIGINT etc

- Cargo.lock
- Cargo.toml
- src/action/interactive.rs
- src/action/mod.rs
- src/main.rs
closes #34 eventually and fixes #59 which was introduced in #58 .
Added the fix for #60 since its just one character..
The current implementation does not restore the cursor on `SIGINT`, `SIGTERM` and `SIGQUIT`. It also does not work when in interactive mode. To simplify things, I removed the `termios` dep and solely restore the `crossterm` and `std::io::stdout` internal changed in the first place when entered interactive mode.
One drawback: hitting `ctrl+c` in interactive mode leads to exit code `1` instead of `130`. Should we fix this?
> Simplified signal handling

- Cargo.toml
- README.md
- src/action/mod.rs
- src/checker/dummy.rs
- src/checker/hunspell.rs
- src/checker/languagetool.rs
- src/documentation/chunk.rs
- src/documentation/mod.rs
- src/suggestion.rs
Avoids drift or regressions.
Add a test to avoid output regressions.
Makes #68 testable.
Add an additional test case (just one for now).
> add a suggestion format test + fix basic single line formatting

- README.md
closes no issue.
I'm using macOS 10.14 and tried to install this tool by `cargo install` but I got 'llvm-config is not found' error on building hunspell-sys.
`brew install llvm` does not install LLVM tools into `$PATH` directory such as `/usr/local/bin` because they confuse LLVM toolchain Xcode installs by default. They are put in `/usr/local/opt/llvm/bin`. `llvm-config` is put in the directory and the path needs to be populated with `$LLVM_CONFIG_PATH` environment variable.
Nothing.
> docs/README: fix installation instruction for macOS with hunspell support

- .concourse.yml
- src/action/bandaid.rs
- src/action/interactive.rs
- src/checker/dummy.rs
- src/checker/hunspell.rs
- src/config.rs
- src/documentation/chunk.rs
- src/documentation/literal.rs
- src/documentation/literalset.rs
- src/documentation/mod.rs
- src/span.rs
- src/suggestion.rs
- src/traverse/iter.rs
- src/traverse/mod.rs
Does all handling of multiline literals, except for displaying, which must be handled in a separate PR.
Closes #37 which requires proper handling of chunks with multiline fragments
* Calculate a full span for common mark files and the associated mapped range.
* Extract spans from multiline fragments.
* `feather_up!` for testability
> cmark files and multiline fragments

- .vscode/settings.json
- src/checker/hunspell.rs
- src/config.rs
Feature, closes #82 .
Additional config for hunspell backend to allow custom regex whitelist or transformation filters.
WIP
> feat/hunspell: add transformation / whitelist support

- Cargo.lock
- Cargo.toml
- src/checker/hunspell.rs
- src/checker/mod.rs
- src/checker/quirks.rs
- src/config.rs
Closes #82.
Extracts quirks and quirks config. Adds extra feature to ignore mistakes which actually just have additional dashes.
> add explicit concat quirks 

- src/suggestion.rs
closes #93 
- Only add additional spaces in case [replacements](https://github.com/drahnr/cargo-spellcheck/blob/master/src/suggestion.rs#L420) has some content (some suggestion).
- Remove additional `|` and white space in the end.
> style/suggestion: no suggestion, less whitespaces

- .concourse.yml
- .config/spellcheck.conf
- .github/pull_request_template.md
- README.md
- src/checker/mod.rs
- src/config.rs
- src/documentation/markdown.rs
Fix a bug when custom search dirs are provided, the default ones are dropped, even if the kv is `search_dirs = []`.
Makes sure the default search paths are kept, but at the lowest priority.
> fix/config: default dirs should always be kept

- README.md
- src/documentation/markdown.rs
> fix/commonmark: insert additional spaces after list items and at list start

- src/action/mod.rs
- src/span.rs
- src/util.rs
Replaces the correction algorithm.
* 🩹 Bug Fix
* 🦚 Feature
Closes #116  .
Previously a line based algortihm was employed which caused some issues in #95 and #116 .
The new implementation works purely on `Span`s wrapped in `Patch`es, which now also handles multiline replacements properly and forces a clear boundary between `Patch` and `Bandaid`.
It's now entirely the concern of the checker to provide sane spans and proper wrapping with comment markers (i.e. `///` ) from within the `Checker`s - this is mostly necessary for #95 .
> refactor/action: rewrite correct_lines purely based on spans

- Cargo.lock
- Cargo.toml
- src/checker/hunspell.rs
- src/documentation/mod.rs
- src/main.rs
- src/suggestion.rs
Makes `hunspell` iterate over content origins in parallel, which yields a huge speedup on machines with more than 2 cores.
* 🦚 Feature
Ref #104  .
Introduce `rayon` to parallelize iteration execution.
This does not yet use a `mpsc` to prepare individual suggestion sets per origin, but merges them into one still. So for _large_ projects there is still a inactivity time noticable. This will be addressed in futures commits.
> feat/hunspell: check content origins in parallel

- Cargo.lock
- Cargo.toml
- demo/src/nested/fragments.rs
- src/documentation/cluster.rs
- src/documentation/developer.rs
- src/documentation/literal.rs
- src/documentation/mod.rs
This PR adds support for spellchecking developer comments in addition to documentation comments.
* 🦚 Feature
snasphysicist
Closes #115
Adds a new module which is responsible for extracting developer comments from the source, converting them into a format (`LiteralSet`) required by the spellchecker and adds them to the data structure which stores the content to be spellchecked.
This also adds a new dependency - `ra_ap_syntax`.
The bulk of the code is in its own, new module (`developer.rs`). We can't use anything from `proc_macro2` since it throws away all information about developer comments so we need to start again from the source file/text, and the new code with tests is quite long (a few hundred lines).
The source is split into tokens, which are then passed through a series of …
> Support for developer comments

- README.md
- src/action/mod.rs
- src/checker/mod.rs
- src/config/mod.rs
- src/documentation/cluster.rs
- src/documentation/mod.rs
- src/documentation/tests.rs
- src/main.rs
- src/reflow/tests.rs
- src/traverse/iter.rs
- src/traverse/mod.rs
* 🩹 Bug Fix
* 🦚 Feature
Closes #132 .
A minor simplification attempt on cli args, and threads a `bool` to the places that need it.
> allow dev comments to be enabled from cli, opt in

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/reflow/mod.rs
* 🩹 Bug Fix
Revamp the args sanitization code, add a unit test for the derived action.
previously `cargo spellcheck --version` was interpreted as to check the _file_ `--version`.
> adjust args parsing issues

- src/reflow/tests.rs
Hello!
I'm maintaining [cargo-spellcheck](https://archlinux.org/packages/community/x86_64/cargo-spellcheck/) in Arch Linux community repository. Today I've faced the following issue while trying to build the latest release:
```sh
(orhun λ cargo-spellcheck) cargo test --locked --release
Compiling cargo-spellcheck v0.6.2-alpha.0 (/home/orhun/gh/cargo-spellcheck)
error[E0425]: cannot find function `load_span_from` in this scope
--> src/reflow/tests.rs:192:38
|
192 |                   let to_be_replaced = load_span_from(&mut content.as_bytes(), replace_span).expect("Test cases are well defined and do not...
|                                        ^^^^^^^^^^^^^^ not found in this scope
...
```
Then I realized `util::load_span_from` import is gone from reflow tests with …
> Add missing import for tests

- demo/src/lib.rs
- demo/src/main.rs
- src/action/bandaid.rs
- src/documentation/literal.rs
- src/documentation/tests.rs
- src/reflow/mod.rs
* 🩹 Bug Fix
* 🦚 Feature
Correctly extracts block doc comments, which previously printed a warning.
Closes #147 .
Adds `CommentVariant` variants and parse them correctly.
There is some work left todo to handle ` * ` line prefixes, see https://github.com/drahnr/cargo-spellcheck/issues/157
hence `reflow` is disabled for those types of comments for now.
> fix/literal: cover /*, /**, and /*!

- Cargo.lock
- Cargo.toml
- src/suggestion.rs
Remove an unused dependency - the only use of `enumflags2` was on `suggestion::Detector`,
but a bitfield of that type is never constructed.
* 🦣 Legacy
> Remove dependency on enumflags2

- src/action/interactive.rs
- src/action/mod.rs
- src/checker/dummy.rs
- src/checker/hunspell.rs
- src/checker/mod.rs
- src/checker/nlprules.rs
- src/checker/tokenize.rs
- src/config/args.rs
- src/config/hunspell.rs
- src/config/mod.rs
- src/documentation/chunk.rs
- src/documentation/cluster.rs
- src/documentation/literal.rs
- src/documentation/mod.rs
- src/errors.rs
- src/main.rs
- src/reflow/mod.rs
- src/span.rs
- src/traverse/iter.rs
- src/traverse/mod.rs
- src/util.rs
Jump to `color_eyre`.
* 🦚 Feature
Closes #127 .
Rather big changeset, unspectacular changes though. Also uses `fs_err` more consistently and remove thus useless `.context` calls which were previously needed.
> feat/errors: migrate to eyre

- demo/member/stray.rs
- src/traverse/mod.rs
Return to the initial traversal via `mod foo` decls and `Cargo.toml`
manifest parsing as soon as one is encountered.
Make traverse more predictable.
* 🩹 Bug Fix
* 🦚 Feature
> fix/traverse: if recurse, collect flat files, otherwise traverse dirs

- build.rs
- src/checker/tokenize.rs
- src/main.rs
Adds some special casing to avoid splitting `isn't` and `he'd` into multiple tokens, to avoid spellchecking with hunspell rightly flaging `isn` and `t`.
* 🩹 Bug Fix
Closes #178
> workaround: assure the tokenizer recognizes i.e. isn't as one token

- src/checker/nlprules.rs
- src/checker/tokenize.rs
Allows `ink!'s` and `should've` to work.
* 🩹 Bug Fix
Closes # .
New tokenization grouping logic.
> tokenize fixup

- Cargo.toml
- README.md
- src/checker/mod.rs
- src/checker/tokenize.rs
- src/config/args.rs
- src/config/mod.rs
- src/documentation/tests.rs
Address a few special cases of tokenization with `)` and friends combined with `'s` variants.
Also add `Cargo.toml` metdata parsing.
```toml
[metadata.spellcheck]
config = "relative/path/to/manifest/config.toml"
```
* :peacock: Feature
* 🩹 Bug 
Adjust the tokenizer to ignore `"` and `(` for pre segements of the token.
> tokenizer quirks

- Cargo.lock
- Cargo.toml
- src/checker/hunspell.rs
* 🪣 Misc
fd-lock 3 replaces `FdLock` with `RwLock`, with an API similar to
`std::sync::RwLock`.
> Port to fd-lock 3.

- README.md
- src/config/args.rs
Iff one argument is passed, also attempt to get the cargo manifest metadata from
the a manifest in the cwd iff one is present and there is none in the target dir specified.
Also moves the `.config/spellcheck.toml` lookup relative to the cwd.
* 🩹 Bug Fix
Closes # .
> fix/arg: check more places for configs.

- Cargo.lock
- Cargo.toml
- src/documentation/cluster.rs
- src/documentation/literal.rs
- src/documentation/literalset.rs
- src/documentation/mod.rs
- src/documentation/tests.rs
Handle:
```rust
/// a
/// ```
#[doc = foo!(b)]
/// ```
/// c
struct X;
```
* 🩹 Bug Fix
* 🦚 Feature
Closes #234 
Add a non-bearing doc-comment variant.
In a few places the assertion of a span-length being equal to the range-length had to be removed. This whole set of changes complicates the source a bit, but also provided a chance to revisit old code, that I wrote when I first leared about `syn`, so it also provided a chance to refactor that part a bit :)
> work with `#[doc=foo!(..)]` style comments

- src/config/args.rs
The first experience counts, so disabling nlprules until
issue #242 is resolved, seems reasonable.
* 🩹 Bug Fix
* 🪣 Misc
Closes #240 
Disable `nlprules` checker by default.
A workaround to improve the first encounter experience. The true issue is #242
> quirk: disable nlprules by default

- src/action/bandaid.rs
- src/action/interactive.rs
- src/action/mod.rs
- src/checker/mod.rs
- src/checker/quirks.rs
- src/documentation/literalset.rs
- src/documentation/tests.rs
- src/reflow/iter.rs
- src/reflow/tests.rs
- src/span.rs
- src/suggestion.rs
- src/util.rs
Prepare for a `cargo clippy` pass, to be less verbose. Currently there are many warnings and hard errors are hard to find.
* 🪣 Misc
> chore: remove redundant `'static` lifetimes for `const C: &str`

- Cargo.lock
- Cargo.toml
- src/documentation/markdown.rs
* 🪣 Misc
Bump deps of `pulldown-cmark` and `isolang`
> chore: bump pulldown-cmark and isolang

- Cargo.lock
- Cargo.toml
- src/config/args.rs
- src/documentation/cluster.rs
- src/documentation/developer.rs
- src/lib.rs
- src/traverse/mod.rs
Update `ra_ap_syntax` which required to rethink the impl. Prepares for the custom `syn` backend removal, once `#[doc=foo!()]` macros work with this backend (untested).
* 🦚 Feature
Update `ra_ap_syntax` and prep for parsing unification
> update ra_ap_syntax and cleanup dev comments parsing a bit

- README.md
- demo/README.md
You can check the result [here](https://github.com/GuillaumeGomez/cargo-spellcheck/tree/fix-markdown-html) (to be noted: github discard inline style).
It will very likely fix crates.io display by adding a `<code>` inside the `<pre>`:
> Fix HTML used in markdown

- Cargo.lock
- Cargo.toml
- src/documentation/markdown.rs
- src/documentation/tests.rs
> ignore html tag content for code and pre

- Cargo.lock
- Cargo.toml
- src/checker/cached.rs
- src/checker/mod.rs
- src/checker/tokenize.rs
- src/config/args.rs
- src/config/mod.rs
- src/lib.rs
- src/main.rs
Adds a caching layer to `nlprules::{Rules,Tokenizer}`, actually regresses tokenizer loading speed by 300us, have yet to check for `Tokenizer`.
* 🩹 Bug Fix
> cache expanded, serialized artifacts and load them from their cached storage format

- docs/automation.md
See #297
Describe usage of cargo-binstall and a GitHub Action which uses cargo-binstall.
I also had some minor changes to the documentation there:
Switch `-m` to `--code` as long options especially in documentation and scripts are easier to read and understand (at least for me).
Switch from `/usr/bin/sh` to `/usr/bin/env bash`. `sh` is most often a symlink to the default shell which easily breaks on systems where the default shell isn't POSIX compliant (like `fish` or `nushell`) or the writer of the script expects bash features.
Until a new release with updated release artefact names is released or the current `latest` is updated with different release artefact names `cargo-binstall` will just fall back to `cargo install`.
> Documentation: cargo-binstall and GitHub Actions

- Cargo.lock
- Cargo.toml
Update to fd-lock 4.0.0, which uses Rust's new `AsFd` trait introduced as part of the I/O safety feature.
This doesn't require any changes to the Rust code in cargo-spellcheck, as fs-err already has the required `AsFd` impls, when enabled with the "io_safety" cargo feature.
* 🪣 Misc
> Update to fd-lock 4.0.0.

- src/checker/mod.rs
- src/suggestion.rs
* 🩹 Bug Fix
Closes #10 .
To remove the duplicated suggestions, the `Vector of Suggestion` is converted once to a `HashSet` and then again to a `Vector`.
This PR tries to resolve the 🔰 part of the issue, but I'm willing to work on further parts of it.
> fix: remove suggestions' duplication

- doc-chunks/src/chunk.rs
- doc-chunks/src/cluster.rs
- doc-chunks/src/developer.rs
- doc-chunks/src/lib.rs
- doc-chunks/src/literal.rs
- doc-chunks/src/markdown.rs
- doc-chunks/src/span.rs
- doc-chunks/src/util.rs
- src/action/interactive.rs
- src/action/mod.rs
- src/checker/cached.rs
- src/checker/dummy.rs
- src/checker/hunspell.rs
- src/checker/mod.rs
- src/checker/nlprules.rs
- src/config/args.rs
- src/lib.rs
- src/main.rs
- src/reflow/iter.rs
- src/reflow/mod.rs
- src/reflow/tests.rs
- src/suggestion.rs
- src/tests.rs
- src/tinhat.rs
- src/traverse/mod.rs
- tests/signal_handler.rs
Most of the time you do not need to use an `&` when calling various format_args! methods - it automatically does that already, plus it causes about 5% perf degradation (compiler cannot optimize most of them due to some limitations discussed at rustlang).
I tried to cleanup a bit, plus a few tiny spacing fixes.  BTW, any reason not to remove `log::` prefix? I.e. add a `use log` at the top?
* 🪣 Misc
> Inline format args, optimize perf

- doc-chunks/src/chunk.rs
- doc-chunks/src/markdown.rs
- docs/configuration.md
- src/checker/dummy.rs
- src/checker/hunspell.rs
- src/checker/nlprules.rs
- src/config/hunspell.rs
- src/reflow/tests.rs
- src/tests.rs
* 🦚 Feature
This PR introduces the option in the configuration to skip checking the footnote references, i.e. under `[Hunspell.quirks]` it introduces a new option, called `check_footnote_references` which is by default set to `true` for backwards compatibility and can be explicitly opted out by setting it to `false`.
As the doc-comment explains it, this is very useful when the markdown uses abbreviations as footnote references (akin to how one would use short link references) but unlike link references this is never skipped.  Which results in the word the footnote had been applied to concatenated with the footnote reference itself, e.g.
```md
Hello[^abc].
```
Will result in checking for spelling against the segment `Helloabc`.
> Implement Optional Footnote References Ignore

- src/config/mod.rs
* 🩹 Bug Fix
Rust 1.77 [merged `unused_tuple_struct_fields` into `dead_code`](https://github.com/rust-lang/rust/pull/118297/), which resulted in the build failing because `#![deny(dead_code)]` is set in `src/lib.rs`.
> fix dead_code compile error

- Cargo.lock
* 🩹 Bug Fix
* 🪣 Misc
Run `cargo update` to update  the dependencies in the lock file. The main motivation is to update `ring` from `0.16.20`(which doesn't support riscv64: https://github.com/briansmith/ring/issues/1182) to `0.17` so that cargo-spellcheck can be built on riscv64 architecture.
> build: run cargo update to make it compile for riscv64

- README.md
* 📙 Documentation : Update the `README.md` to provide a detailed installation guide for mac & linux users.
Closes #320  .
> Add installation guide for mac / linux users

- .config/lingo.dic
- .config/spellcheck.toml
- Cargo.lock
- Cargo.toml
- doc-chunks/src/cluster.rs
- doc-chunks/src/errors.rs
- src/checker/dictaffix.rs
- src/checker/hunspell.rs
- src/checker/mod.rs
- src/checker/spellbook.rs
- src/checker/zspell.rs
- src/config/args.rs
- src/config/hunspell.rs
- src/config/mod.rs
- src/suggestion.rs
Currently doesn't support suggestions. Will obsolete `hunspell` eventually.
Add `zspell` based checking. Helpful since `hunspell` has some concurrency issues, see #332 
* 🦚 Feature
* Currently we get a different set of detections.
* `suggestions` are currently not supported
> feat/zspell: introduce featre `zet`, using `crate:zspell`
